const GOOGLE_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbxt8qWmwjHmwsLUQ3TKSqMzLq2rG5_EKw5wcVLBfh4Ihh7Ku7kwQ0jB1ug8IvtnBJo7NQ/exec";

const SENARAI_MURID = {

"5 Mumtaz": [
"AB MUHAMMAD NURASYRAF BIN AB AZIS",
"ABDULLAH BIN SAINI",
"AFIFAH FITRIYAH BINTI ABRAHAM",
"DAVINA ZAVIERA BINTI RIZAN HARDINATA",
"DAYANG IZZ RYNA BINTI AHMAD",
"DAYANG NUR SHAFIYYAH BINTI NASIP",
"ERISHA DAMIA BINTI NASRI",
"HAMISYA AMANI BINTI HAMSAH",
"LINA AFIQAH BINTI ABDULLAH",
"MOHAMAD DZAQERUL HAMZAH BIN MOHAMAD RIDWAN",
"MOHAMMAD HARITH MIKAL BIN ISMAIL",
"MOHAMMAD SHAQIRIN SARIPUDDIN",
"MOHAMMAD THAQIF HARRAZ BIN SABRI",
"MUHAMAD IZZAT BIN MUHAMAD SUFRI",
"MUHAMMAD ARSYAD MALIQRIN SAHRUL",
"MUHAMMAD ARSYAD MIQAEL BIN SAHRUL",
"MUHAMMAD FAIZ DAM BIN SYAMSUDDIN",
"MUHAMMAD HADIFF BIN SAMBRAN",
"MUHAMMAD KAMARUL BIN KAMAL",
"MUHAMMAD NAUFAL LUTHFI BIN MOHD SYAZWAN",
"MUHAMMAD SYAFIQ AIMAN BIN AHMAD",
"MUHAMMAD SYAHFIQ BIN JUPRI",
"MUHAMMAD SYAHRIZAN UQASYA BIN REDUWAN",
"MUHAMMAD ZAHIR ARRAYYAN BIN AZMAN",
"NUR AISYAH ZULAIKHA BINTI MOHD ROSMAN",
"NUR DAMIA QAISARA BINTI RAMLAN",
"NUR FITRI SYAFIYAH BINTI ADZHAR KHAN",
"NUR ZARA ZULAIQAH BINTI ABDULLAH",
"NUR QISYA ADELIA BINTI HUSSIEN",
"NURUL SHAFIQAH SENROSE BINTI ASBIDUN",
"RAYYAN BIN SUHAIMI",
"RAZIEQ AZFAR BIN RUSLAN",
"RISOAH ADRIANA BINTI RAIS"
],

"6 Jayyid": [
"AIRIS NUR RAYSHA AMANDA BINTI RIDUAN",
"ARIZ FAIQH BIN MOHD ROZADY",
"AUFA HANIFAH BINTI JUARI",
"IZZAT NAZHAN BIN SUMARDI",
"LINDA QAISARAH BINTI RAILAN",
"MAHIRAH ATHILAH BINTI M SABRAN",
"MUHAMMAD AFIF ARSYAD BIN HASRIN",
"MUHAMMAD AIMAN BIN AMBO MASSE",
"MUHAMMAD AMMAR SYAWAL BIN SUDEYANSHAH",
"MUHAMMAD ARIQ ADAM BIN SANUDIN",
"MUHAMMAD DANISH ZAFWAN BIN PAISAL",
"MUHAMMAD DZAR DZIKRI BIN MARINDO @ ABD KARIM",
"MUHAMMAD FAIZ IZZUDDIN BIN MOHD FAIROS",
"MUHAMMAD FARIZ IZZUDDIN BIN MOHD FAIROS",
"MUHAMMAD HAZIQ SYAKIR BIN AMING",
"MUHAMMAD LUTHFI WAFI BIN ABDULLAH",
"MUHAMMAD MAHDY BIN MAZLAN",
"MUHAMMAD YUZWAN WAFIY BIN YUSUF",
"NUR ADILAH BINTI ABDUL MALIK",
"NUR ERYNANAURAH BINTI JAMAL",
"NUR FARAH FADILAH BINTI MOHD ARDY",
"NUR HUMAYRAA DELISYAH BINTI HERMAN",
"NUR GHAYRIN AFIQAH BINTI JAMIDI",
"NUR SUBAYYA AZZAHRA BINTI SAHIRUL",
"NUR ZHAFIRAH BINTI ABDUL RASHID",
"NURANIS FATIHAH BINTI JAMAL",
"NURUL SUHADA BINTI SURYAMAN",
"NURZAHRA ZAFIRAH BINTI ASIS",
"RIZQ IRFAN BIN MOHD AZRUL",
"SITI NUR ADIBAH SYAHIRAH BINTI AMRANI",
"SITI NUR ALYANABILAH BINTI HASRIN",
"SITI NURFARZIREKIN BINTI HERY",
"YASIN MUHAMMAD KHAIRUL BIN YUSRAN"
]

};

let dataMarkah = [];

function isiSenaraiNama() {

const kelas =
document.getElementById("kelas").value;

const namaSelect =
document.getElementById("nama");

namaSelect.innerHTML = "";

SENARAI_MURID[kelas].forEach(nama => {

const option =
document.createElement("option");

option.value = nama;
option.textContent = nama;

namaSelect.appendChild(option);

});

}

async function loadData() {

try {

const response =
await fetch(GOOGLE_SCRIPT_URL);

const data =
await response.json();

dataMarkah = [];

for (let i = 1; i < data.length; i++) {

dataMarkah.push({
kelas: data[i][1],
nama: data[i][2],
ujian: data[i][3],
markah: Number(data[i][4]),
gred: data[i][5],
tp: data[i][6],
status: data[i][7]
});

}

paparData();

} catch (err) {

console.log(err);

}

}

function paparData() {

const tbody =
document.getElementById("jadualMarkah");

tbody.innerHTML = "";

dataMarkah.forEach((item, index) => {

tbody.innerHTML += `

<tr>
<td>${index + 1}</td>
<td>${item.kelas}</td>
<td>${item.nama}</td>
<td>${item.ujian}</td>
<td>${item.markah}</td>
<td>${item.gred}</td>
<td>${item.tp}</td>
<td>${item.status}</td>
</tr>

`;

});

}

document.addEventListener(
"DOMContentLoaded",
function () {

isiSenaraiNama();
loadData();

}
);
